BOT_PATH = './bot.rb'

KEYS = [
    "./discord_token.key",
    "./discord_client_id.key",
]

def check_keys
    for key in KEYS do
        unless File.file?(key)
            puts "Missing #{key}..."
            return false
        end
    end
    return true
end

task :run do
    puts system("ruby #{BOT_PATH}") if check_keys
end